language: node_js

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/
    - /^rc-.*$/

script:
  - npm run test
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)
